### ISSUE TITLE
Issue with downloading avctKVM

### ISSUE THREAD

**Issue by hyperexpert** [DomiStyle/docker-idrac6#1]
I have few Dells with iDrac 6 Enterprise. Web interface, console, etc, all work however, when running this script, I get:

wget: server returned error: HTTP/1.1 404 Not Found
Failed to download avctKVM.jar, please check your settings

[services.d] stopping services
![screenshot from 2018-09-24 20-52-26](https://user-images.githubusercontent.com/22566847/45992073-af837980-c03c-11e8-9816-adee3ef32644.png)

Hope you can assist with why I am getting this error.

**Comment by hyperexpert** [comment]
I cant! I am using the IP directly and not FQDN like so:

`sudo docker run -p 5800:5800 -p 5900:5900 -e IDRAC_HOST=192.168.10.10 -e IDRAC_USER=[USER] -e IDRAC_PASSWORD=[PASSWORD] domistyle/idrac6`

I can logon to iDrac and download console viewer jnlp file, however, I cant go to your /software/avctKVM.jar link. I wonder if this was changed, when I open my downloaded .jnlp file with text editor, I see the following:

```
<?xml version="1.0" encoding="UTF-8"?>

<jnlp spec="1.0+" codebase="https://192.168.10.10/Applications/dellUI/Java" >
     <information>
        <title>JViewer</title>
        <vendor>Dell Inc.</vendor>
        <description kind="one-line">JViewer Console Redirection Application</description>
        <description kind="tooltip">JViewer Console Redirection Application</description>
        <description kind="short">
            JViewer enables a user to view the video display of managed server via KVM.  
            It also enables the user to redirect his local keyboard, mouse for managing the server remotely.
        </description>
    </information>
	<security>
		<all-permissions/>
	</security>
    <resources>
        <j2se version="1.5+" initial-heap-size="128m" max-heap-size="256m" />
        <jar href="release/JViewer.jar"/>
    </resources>
    <resources os="Windows" arch="x86">
    	<j2se version="1.5+"/>
    	<nativelib href="release/Win32.jar"/>
    </resources>    
    <resources os="Windows" arch="amd64">
           <j2se version="1.5+"/>
           <nativelib href="release/Win64.jar"/>
    </resources>
    <resources os="Linux" arch="x86">
    	<j2se version="1.5+"/>
    	<nativelib href="release/Linux_x86_32.jar"/>
    </resources>    
    <resources os="Linux" arch="i386">
    	<j2se version="1.5+"/>
    	<nativelib href="release/Linux_x86_32.jar"/>
    </resources>    
	<resources os="Linux" arch="x86_64">
	 	<j2se version="1.5+"/>
    	<nativelib href="release/Linux_x86_64.jar"/>
	</resources>	
	<resources os="Linux" arch="amd64">
	 	<j2se version="1.5+"/>
    	<nativelib href="release/Linux_x86_64.jar"/>
	</resources>				
    <application-desc>
       <argument>192.168.10.10</argument>
<argument>5901</argument>
<argument>aeAVnoKUiHAa5PH3</argument>
<argument>1</argument>
<argument>0</argument>
<argument>3668</argument>
<argument>3669</argument>
<argument>511</argument>
<argument>5900</argument>
<argument>1</argument>
<argument>EN</argument>

    </application-desc>
</jnlp>
```


I can successfully download https://192.168.10.10/Applications/dellUI/Java/release/JViewer.jar or any of the other files listed in that text. Anything else is a 404

**Comment by DomiStyle** [comment]
Are you using iDRAC 5? If so, check out https://github.com/ncerny/docker-idrac.
It supports iDRAC 5 and iDRAC 6.

**Comment by hyperexpert** [comment]
Thank you for the link. When I log on, my servers show iDrac 6 Enterprise. I tried the other repo but also did not work. I think I will just stick with a local VM for now. I was just hoping for an easier way.

Thanks again for all the efforts.

**Comment by DomiStyle** [comment]
I have never seen an iDRAC 6 that loads a JViewer.jar, what iDRAC version are you running? All my servers with iDRAC 6 Enterprise work fine with the container.

**Comment by hyperexpert** [comment]
Sorry for the delayed response. I have a Dell M610 that originally came with iDrac5 but after the firmware updates, it now says iDrac 6 Enterprise. I tried the iDrac 5 docker image in your link and still did not work. I will post the error there for reference but this is what I get

![screenshot from 2018-10-22 21-36-57](https://user-images.githubusercontent.com/22566847/47336371-4f382580-d644-11e8-97fa-6e4e2df80b34.png)

**Comment by hyperexpert** [comment]
Welp, cant post the issue there :/ I am trying this on Ubuntu 18.04 and 18.10 btw with the same results

**Comment by DomiStyle** [comment]
I took a look at the forked iDRAC image and it seems like the version detection works by requesting ```https://${IDRAC_HOST}/page/login.html``` for iDRAC 5 and ```https://${IDRAC_HOST}/images/Ttl_2_iDRAC6_Ent_ML.png``` for iDRAC 6.

In your case neither exists because your log never shows you reaching either version. So it seems like you have some strange mixture between iDRAC 5 and iDRAC 6 going on.

I pulled the changes and removed the version check to force iDRAC 5. As soon as the image is built you can use domistyle/docker-idrac6:dell-m610 and give it a try.

**Comment by hyperexpert** [comment]
Thank you so much for helping me out with this! However, can you please edit the download link from: https://IP_ADDRESS/Java/release/JViewer.jar to: https://IP_ADDRESS/Applications/dellUI/Java/release/JViewer.jar

I can manually download the file with https://IP_ADDRESS/Applications/dellUI/Java/release/JViewer.jar but not with the /Java/release/ URL

I also used **domistyle/idrac6:dell-m610** to pull the image ;)

![screenshot from 2018-10-25 14-29-31](https://user-images.githubusercontent.com/22566847/47531590-ed093b80-d862-11e8-987d-74fd3901486c.png)

**Comment by DomiStyle** [comment]
> I can manually download the file with https://IP_ADDRESS/Applications/dellUI/Java/release/JViewer.jar but not with the /Java/release/ URL

Updated the image, hopefully the paths are correct now.
