### ISSUE TITLE
Incorporate keycode fixes

### ISSUE THREAD

**Issue by maedoc** [DomiStyle/docker-idrac6#11]
The arrow keys don't work (for me) which is pretty essential to navigating the BIOS, for example.  It seems there's a nice fix [over here](https://github.com/anchor/idrac-kvm-keyboard-fix), and it could be nice to build that into this image.  I have tested this fix, and it appears to work correctly.  It appears sufficient to just compile the C file and `LD_PRELOAD` it in the idrac wrapper script when launching java.

**Comment by DomiStyle** [comment]
For some reason my arrow keys work fine without the fix but stop working with the fix. What keyboard layout do you use?

If you need that fix in order for the arrow keys to work I can include it as an optional fix with environment variables.

**Comment by maedoc** [comment]
english US, maybe your idracs are older/newer than mine?  the env var is a good idea.

**Comment by maedoc** [comment]
I've R510s w/ iDRAC6 Virtual Console 1.5 (build 1.0.0.78), maybe I should look for a firmware update.

Thanks, by the way, for building this, it's super handy.

**Comment by DomiStyle** [comment]
Just pushed your changes to master, you can activate them by setting IDRAC_KEYCODE_HACK. Let me know if that works for you.

> Thanks, by the way, for building this, it's super handy.

You're welcome. Thanks for your contribution.

**Comment by maedoc** [comment]
Great, thanks for the explanation.  I’ll try this at the next chance.

**Comment by kategray** [comment]
The arrow keys don't work on my system.  US keyboard.

**Comment by kategray** [comment]
Keycode hack fixes things for me.  Thank you.
