### ISSUE TITLE
mount folder 

### ISSUE THREAD

**Issue by Sndan** [DomiStyle/docker-idrac6#15]
what is the best way to mount and share files ?
I used this command 
`docker run -v F:/data:/vmedia -d -p 5800:5800 -p 5900:5900 -e IDRAC_HOST=192.168.100.178 -e IDRAC_USER=root -e IDRAC_PASSWORD=calvin domistyle/idrac6`

but the vmedia file is empty ?!

any help would be appreciated

thanks

**Comment by DomiStyle** [comment]
Is there anything in the F:/data folder on the host? Did you grant Docker for Windows permission to use your F drive?

**Comment by Sndan** [comment]
there is an iso file 
and yes I shared c and f drives with docker

**Comment by DomiStyle** [comment]
Try resetting the credentials for your drives under Settings -> Shared Drives. Recreate the container afterwards.

It's another Docker for Windows bug.

**Comment by MatthewEvolving** [comment]
Hi, thanks for this, I am trying to get the ISO to mount, and managed to get the drive letter and /vmedia folder to show in the iDRAC "virtual media" add image dialogue. 

**Unfortunately I do not see the ISO in the folder.** I have the folder on Windows mounted and shared with "everyone" READ. Recreated the container numerous times. 

Any ideas how you got this working?
Thanks!
