### ISSUE TITLE
Did you make any progress getting Virtual Media to work?

### ISSUE THREAD

**Issue by simonk83** [DomiStyle/docker-idrac6#2]
Sorry for making an issue just to comment.  Really great work with this, it's awesome not having to use Java, but it'd be really great to be able to use Virtual Media as well.   Just wondering if you ended up looking into that or it just ended up being too hard?

**Comment by DomiStyle** [comment]
I shortly looked into it but since I'm not a Java guru I have no idea why it isn't loading the libraries. They exist and the library path is set.

If somebody gets them working I'm more than happy to accept a pull request.

**Comment by wer38** [comment]
Well too bad i dont know java :( really handy tool btw

**Comment by DomiStyle** [comment]
> I think you are missing a lib for this to work. see lib/avmWinLib.so

I was under the impression that these are for Windows only but I will give it a try. I also haven't actually tried extracting the .so files from the jar files so I might give that I try when I have some time.

Thanks for the link.

**Comment by antpk** [comment]
Yea the dlls aren't what you need. I tried extracting the .so files and it does change the behavior. It tries to load the native library now but crashes the jvm. Probably needs a specific libgcc/libc or equivalent being present. Haven't checked but what I was going to look at next was what the base image for the vnc client is using. Suspect it needs to be changed from alpine.

**Comment by DomiStyle** [comment]
> Haven't checked but what I was going to look at next was what the base image for the vnc client is using.

jlesage/baseimage-gui also has an Ubuntu and Debian version, but the Dockerfile probably needs adjustments to use apt-get instead of apk.

Some also say that the libraries need to be in the root folder together with the main jar, so it might also be worth extracting all the .so files and placing the .jar and the .so files in both the lib and the root folder just to be sure.

If the change to Ubuntu/Debian doesn't work it might also be worth it to look into using the Oracle JRE instead of OpenJDK, maybe there's an issue there.

**Comment by spaghettiBaguette** [comment]
Just to jump in here, from some discussions I've seen it looks like using the 32bit java would resolve this issue. I've had no luck trying to find a way to actually install the 32bit version though so I can't say for sure

**Comment by spaghettiBaguette** [comment]
Scratch the above, may have figured out the issue and it's completely different. Will update shortly

**Comment by spaghettiBaguette** [comment]
Following up on this, I seem to be hitting the same issue as antpk, where loading the .so files crashes the JVM. I can't find any way to get logging on what's actually crashing though

**Comment by DomiStyle** [comment]
> Following up on this, I seem to be hitting the same issue as antpk, where loading the .so files crashes the JVM.

There's a few things that can still be tried:

* Ubuntu instead of Alpine
* x86 OpenJDK instead of x64 OpenJDK
* Oracle JVM instead of OpenJDK
* OpenJDK 6 instead of 7

**Comment by antpk** [comment]
Just to update. I managed to get it to work. It's a little not fully automated yet. Had to use ubuntu1604 and jdk7 from ppa.

**Comment by DomiStyle** [comment]
> Just to update. I managed to get it to work. It's a little not fully automated yet. Had to use ubuntu1604 and jdk7 from ppa.

Which ppa and did you extract any of the libraries or just used the jar files directly?

**Comment by antpk** [comment]
Sorry @DomiStyle , didnt see the reply till now. I extracted the .so files and had to keep the jar files too. I have uploaded my current config to my github. See https://github.com/antpk/docker-idrac6
I use docker-compose to map the app folder/build. The bit that is missing is downloading the jars and extracting them. Sorry was wanting to get that done but didn't have time and what I have now is working for me. I know its not perfect.

**Comment by DomiStyle** [comment]
> Sorry was wanting to get that done but didn't have time and what I have now is working for me. I know its not perfect.

No worries, will take a look at it once I get home.

**Comment by DomiStyle** [comment]
Libraries are now correctly loaded in the latest version.
https://github.com/DomiStyle/docker-idrac6/releases/tag/v0.3

**Comment by simonk83** [comment]
Nice work guys :)
