### ISSUE TITLE
Alternative Ports on the iDRAC

### ISSUE THREAD

**Issue by RavHilton** [DomiStyle/docker-idrac6#29]
I see that I can change the HTTPS port that I connect to the remote iDRAC and that is working, but I also need to have the Remote Presence port changed from the default of 5900 to something else (in this case 24100) as I have multiple Dell servers on a site and need to address each from remotely, which requires using different ports.

I have 3 servers on this site, using Remote Presence of 24100, 24200 and then 24300 which allows me to access the first, second and third servers over an appropriate (changed) port number that I can remember.  This matches with the HTTPS ports on these machines being 24143, 24243 and 24343 respectively.

Is there any chance of having the ability to use a non-standard Remote Presence port number on the iDRAC?  This would allow me to use this (otherwise really nice and handy) Docker container.

**Comment by DomiStyle** [comment]
Can you try using domistyle/idrac6:idrac-ports and setting IDRAC_VPORT to your port numbers?

Although I wouldn't really recommend doing this unless you are in a private environment. Not a good idea to expose iDRAC to the internet.

**Comment by DomiStyle** [comment]
@RavHilton Did you have time yet to try it out?
