### ISSUE TITLE
RPi4 Docker: exec format error

### ISSUE THREAD

**Issue by Narbss** [DomiStyle/docker-idrac6#32]
Having an issue where I get the error:
standard_init_linux.go:211: exec user process caused “exec format error”

Tried multiple attempts installing the container, and always get this same error.
Docker is running on a Raspberry Pi 4, and iDRAC6 is on an R710 with the most recent firmware installed.

Thanks

**Comment by DomiStyle** [comment]
There is no ARM version of this image (yet), hence why it won't run on a Raspberry Pi.

https://github.com/DomiStyle/docker-idrac6/issues/4

**Comment by Narbss** [comment]
Well somehow I totally missed that! Thanks for the follow up, will definitely install on a different machine though and look forward to the ARM branch.
